import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="w-full py-2 px-4 flex-shrink-0">
      <div className="container mx-auto text-center text-xs text-gray-600">
        <p>
          Disclaimer: Recipes and information are generated by Cook AI. Always use your best judgment.
        </p>
      </div>
    </footer>
  );
};

export default React.memo(Footer);